---
  deviceName: "muse_lsl_with_open_vibe"
  samplingRate: 256 # Hz

  numberOfChannels: 4

  channelNames: "Todo" 
  # TP9, AF7, AF8, TP10

  # For bandpass filtering
  lowcutFreq_bandpass: 0.5 # Hz
  highcutFreq_bandpass: 60 # Hz

  # Bandstopp filtering
  lowcutFreq_bandstopp: 49 # Hz
  highcutFreq_bandstopp: 51 # Hz

  # replace outliers
  lowerThreshold: -200
  upperThreshold: 200

  maxFaultyRate: 0.15 # Lower -> more better quality epochs | Higher -> more noisy epochs
  epochWindowSize: 2 # in seconds 
  overlap: 1 # in seconds - or insert None for no overlap

  # Define the frequency bands
  frequencyBands : 
    Delta:
      - 0.5
      - 4
    Theta:
      - 4
      - 8
    Alpha:
      - 8
      - 12
    Beta:
      - 12
      - 30
    Gamma:
      - 30
      - 50

  # How many epochs should be included to calcualte a mean or standard deviation value
  epochSizeCalculation: 5