---
  deviceName: "neuroscan"
  samplingRate: 1000 # Hz
  resampleRate: 256 # Hz - Set to 0 if the normal sampling should be used

  numberOfChannels: 40

  # TODO
  channelNames: "Todo" 
  # HEOL|FP1|FP2|VEOU|VEOL|F7|F3|FZ|F4|F8|FT7|FC3|FCZ|FC4|FT8|T3|C3|CZ|C4|T4|TP7|CP3|CPZ|CP4|TP8|A1|T5|P3|PZ|P4|T6|A2|O1|OZ|O2|FT9|FT10|PO1|PO2

  # For bandpass filtering
  lowcutFreq_bandpass: 0.5 # Hz
  highcutFreq_bandpass: 250 # Hz - has to be that high, probably because of that high sampling rate

  # Bandstopp filtering
  lowcutFreq_bandstopp: 49 # Hz
  highcutFreq_bandstopp: 51 # Hz

  # replace outliers
  lowerThreshold: -200
  upperThreshold: 200

  maxFaultyRate: 0.15 # Lower -> more better quality epochs | Higher -> more noisy epochs
  epochWindowSize: 2 # in seconds 
  overlap: 1 # in seconds - or insert None for no overlap

  # Define the frequency bands
  frequencyBands : 
    Delta:
      - 0.5
      - 4
    Theta:
      - 4
      - 8
    Alpha:
      - 8
      - 12
    Beta:
      - 12
      - 30
    Gamma:
      - 30
      - 50

  # How many epochs should be included to calcualte a mean or standard deviation value
  epochSizeCalculation: 5